version: '2'
services:
  nginx:
    build: devops/docker/nginx
    container_name: quickpay.nginx
    volumes:
      - .:/usr/share/nginx
    ports:
      - "8080:80"
  php:
    build: devops/docker/php
    container_name: quickpay.php
    volumes:
      - .:/usr/share/nginx
    ports:
      - "9000:9000"
  db:
    image: mariadb:10.3.0
    container_name: quickpay.db
    environment:
      MYSQL_DATABASE: "db_quickpay"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"