version: '2'
services:
  nginx:
    build: devops/docker/nginx
    container_name: quickpay.nginx
    volumes:
      - .:/usr/share/nginx
    ports:
      - "8092:80"
  php:
    build: devops/docker/php
    container_name: quickpay.php
    volumes:
      - .:/usr/share/nginx
    ports:
      - "9000:9000"